"""Hand-written redactions for rows where the automatic sentence filter in
redact_test_set.py is not enough: the verdict sits inside a descriptive
sentence, legal reasoning survives the keyword filter, or the filter dropped a
purely factual sentence. Rule applied throughout: keep what the system does,
who uses it, what data it uses, what its output is used for and how humans are
involved; remove every legal conclusion or legal test applied to it."""

OVERRIDES = {
"anx3-008": "A CCTV facial recognition system at the entry to a stadium to detect blacklisted individuals forbidden to enter the stadium via direct access control, where natural persons need to actively step in front of the AI system to get access to the stadium.",
"anx3-010": "AI systems for smart homes/residential areas: An AI system intended to be used to authenticate or verify the identity of an individual to give access to a home or residential area by scanning facial images, irises, voice (voiceprint identification), or fingerprints at the entrance and which grants access after a successful check against a reference database made up of biometric data which the relevant individual agreed to register. The individual agreed to register and consciously presents themselves at the entrance.",
"anx3-011": "Smart corridor AI biometrics system: an AI system that captures the facial images of individuals from several angles in a short corridor or passage and compares those images against a biometric database of persons that have registered with the system through which those persons can enter a concert, stadium, major public event at a city square, etc., without stopping, whereas unregistered persons are approached and ejected by security staff or by automatic door systems, depending on the application. Such systems are used solely to gain access to a service/premises, for persons who registered with the system beforehand.",
"anx3-013": "An AI system that uses a voice sample collected with the individual's active involvement to carry out language/dialect analysis in order to identify the country and region from where a person originates in the context of migration and asylum processes. The voice sample is matched against a pool of accredited voice samples to substantiate country of origin.",
"anx3-016": "AI systems with the sole purpose of anonymising personal data, such as biometric systems which are intended to be used solely for the purpose of enabling cybersecurity and personal data protection measures.",
"anx3-025": "AI system intended to be used as a content moderation tool. The AI system scans text/pictures to identify illegal or inappropriate content, categorising content based on specific indications (e.g., extreme content that may reveal political opinions). The categorisation is not made on the basis of biometric data.",
"anx3-027": "An AI system for the gaming industry that is intended to measure a gaming experience to further improve the product (real-life gaming experience). The AI system tracks body posture, facial expressions, eye closures and gazes to measure the reaction of the player, including their excitement, anger, frustration, amusement; analyses the above-mentioned recorded data to identify relevant elements of the gaming experience that needs improvement.",
"anx3-028": "An AI-based solution to maintain order during concert events. The AI system is installed in cameras at walls or ceilings; screens the mood of the audience, e.g., voices, faces and movements; when the system finds that the mood is getting aggressive in a certain area of the stadium, more security personnel is sent to that area. The system screens the emotions of individual participants to assess the mood of the audience.",
"anx3-029": "An AI system used in call centres to infer emotions of customers. The AI system analyses customers' voices and evaluates vocal tone, pitch and volume to gauge customer satisfaction level for statistical reasons, to identify the moment to route them to a human agent (e.g., anger), for troubleshooting purposes, or to enhance customer care business unit. These AI systems deduce from the customer's voice their emotions, e.g., if they are happy or angry.",
"anx3-030": "Smart watch mood monitor/wearable device. The AI system is integrated into a smart watch to measure biometric data (e.g., voice, heart rate) and monitor user emotions (e.g., sad, curious, happy, bored) to assist users in recognising their emotional state and provide emotional improvement suggestions. The results are disclosed only to the user.",
"anx3-031": "An AI system intended to be used by the automotive industry to help prevent accidents by detecting when a driver loses focus (i.e., drowsiness, falling asleep, experiencing sudden health issues). The AI system tracks body posture, facial expressions, eye closures and gazes via installed cameras and motion detectors in a vehicle; analyses the collected data to alert the driver or assume control of the vehicle, and safely bring it to a stop.",
"anx3-032": "A TV broadcaster uses a device that tracks how many times its news presenters smile at the camera, i.e. the mere observation of readily apparent expressions.",
"anx3-033": "An AI system used as a fire alarm controlling system in cloud computing centres.",
"anx3-036": "An AI system intended to be used to monitor road traffic and to adjust traffic lights accordingly.",
"anx3-037": "An AI system intended to be used in the recognition of heavy objects on vulnerable bridges and quaysides, to help prevent the collapse of bridges and quay walls. The failure of the AI system could result in potential collapse not being detected on time and natural persons on the bridges and quay walls being at risk when they collapse.",
"anx3-038": "An AI system intended to be used to link real-time water level data to lock management for road traffic (e.g. in flood-risk scenarios). Such a system monitors and detects situations that may directly lead to physical harm to natural persons or physical damage to property.",
"anx3-040": "An AI-enabled traffic flow optimisation system based on real-time data collection: a traffic data analytics platform enabling intelligent analysis for flow optimisation functions. It provides insights but does not directly trigger changes in the traffic management. Traffic systems can function without it.",
"anx3-051": "Automated admissions systems intended to be used to review and evaluate student applications, transcripts, and test scores to determine eligibility for admission to an educational institution. The system's evaluation and recommendation determine the outcome of the admissions decision.",
"anx3-053": "Vocational training assignment AI tools intended to be used by a regional employment agency to process applicants' prior education records, completed certifications, and standardized aptitude test results to match individuals to available apprenticeship programs. Such systems apply predefined eligibility criteria, such as minimum qualifications required for each program and capacity limits, to assign candidates to appropriate training slots.",
"anx3-057": "AI systems supporting the processing of applications to be used by an education institution for file handling, such as indexing, searching, text and speech processing, as well as for the translation of documents provided along with applications, and for extracting, transforming, and organising the data collected into a meaningful and usable format. They are intended to facilitate the organisation and review of applicant files.",
"anx3-058": "AI-enabled admissions decision review tools intended to be used by an educational institution to review and analyse ex post admissions decisions made by an admissions committee, providing a quality control check on the admissions process and supporting future decision-making processes, rather than making decisions.",
"anx3-060": "AI-enabled grading and feedback systems intended to be used to evaluate students' assignments, such as tests, quizzes, and exams which count towards a final evaluation. The AI system analyses the results of assignments and proposes grades.",
"anx3-061": "AI-enabled personalised learning assistant intended to be used to provide recommendations and feedback to students on their progress by generating reports at the end of each unit, which include grades, areas of strength and weakness, and recommendations for improvement. The system provides ongoing feedback to students, and its output is also used by the teacher to inform decisions about students' grades at the end of the academic period.",
"anx3-072": "AI-enabled pre-assessment tool intended to be used to help educators prepare for the assessment of a student's readiness for a particular level of education or training, based on data about the student's prior education and work experience, generating a set of questions and topics that the educator can use to assess the student's readiness. The system's output is used by educators to inform their assessment methodology; it does not itself make decisions about the level of education an individual will receive or be able to access.",
"anx3-074": "AI-enabled proctoring system for exam certification intended to be used by an educational or vocational training institution to monitor test-takers for prohibited behaviour during a certification exam, such as accessing unauthorized materials or communicating with someone else during the exam, by using a combination of facial recognition, keystroke analysis, and screen monitoring.",
"anx3-075": "AI-enabled exam monitoring system intended to be used by an educational institution to monitor and detect prohibited behaviour during in-person exams, such as the use of unauthorized materials or devices, by using facial recognition and object detection.",
"anx3-076": "AI system intended to be used by an educational institution to check homework or assignments for plagiarism against a database of existing content. It analyses submitted work produced in a non-supervised environment and does not involve live monitoring or real-time behavioural analysis during tests.",
"anx3-077": "AI system for non-academic student behaviour monitoring intended to be used by an educational institution to monitor and detect student behaviour in the cafeteria, hallways, and other non-testing environments and to alert staff to potential incidents of bullying, harassment, or other undesirable behaviour. It serves non-academic purposes, such as maintaining a safe and orderly school environment, and does not involve the evaluation of student academic performance.",
"anx3-079": "Identity verification: An AI system intended to be used during a test to automatically process students' identity verification documents, such as IDs or biometric data like facial recognition scans, to confirm that the person taking the test matches the registered candidate. The system does not decide whether the student can proceed with the exam or whether sanctions apply in the case of misrepresentation; these decisions are made by the human proctor.",
"anx3-080": "AI systems intended to be used as an automated job matching and ranking tool designed to assist internal and external recruiters in the recruitment and selection processes by analyzing and filtering candidates. Such a system processes structured and unstructured data (e.g., CVs, skills, education, past placements, cognitive, social and emotional competencies) and compares it to job descriptions or historical hiring data to generate quantitative scores, rankings (e.g., 'top 5 candidates'), and/or qualitative fit categories (e.g., 'high fit,' 'low fit'). These outputs are used to shortlist candidates for internal and external recruiters, who retain discretion to review, override, or supplement algorithmic recommendations. However, the system's rankings and scores serve as a primary input for decision-making.",
"anx3-084": "AI system intended to be used for scoring applicant answers in a recruitment process. An AI system is intended to be used to evaluate written or oral responses given by job applicants during an online assessment. The system assigns each applicant a numerical score based on linguistic and substantive criteria, then generates a ranking used to determine who is invited to the interview stage.",
"anx3-085": "AI system intended to be used to support apprenticeship recruitment at a commercial firm. A firm uses an AI system to support the recruitment of apprentices. The system is applied to manage and process applications for apprenticeship positions, potentially by screening CVs, matching applicants to roles, or generating shortlists based on pre-defined criteria such as qualifications or age.",
"anx3-086": "AI system intended to be used to place targeted job advertisements to specific users on social media. The system collects and analyses a wide range of data navigation patterns and user characteristics. Advertisers provide targeting criteria, such as age, educational and professional background, or sector, and the system identifies and prioritises potential audiences for job vacancies.",
"anx3-088": "AI system intended to be used to perform background checks on job applicants during recruitment. The system aggregates and analyses multiple types of data. Standard inputs include official records, such as education and professional certifications, employment history, social network history, and credit or financial data, where legally permissible. The system also incorporates open-source and online information. Employers or recruiters receive outputs in the form of composite risk scores, categories such as 'low', 'medium' or 'high', or specific alerts highlighting potential issues (e.g., unexplained employment gaps, flagged financial liabilities, or controversial online activity). These outputs can be used as filters in high-volume hiring, where flagged candidates may be deprioritized or excluded before a caseworker reviews their file. Human review is formally part of the process, but in practice the system's output heavily influences which candidates advance.",
"anx3-091": "AI system intended to be used for employer reputation monitoring. A company uses an AI system to scan online platforms and social media for comments or reviews mentioning the employer, with the purpose of tracking the organisation's reputation as a workplace and identifying general trends in how the company is perceived by potential applicants. No analysis or tracking of specific comments or specific users (which are anonymized at collection) is undertaken.",
"anx3-093": "AI system intended to be used for assisting candidates in tailoring their CV to specific open positions. The AI system analyses the candidate's CV along with the description of the open position provided by the candidate. Based on these elements, the AI tool recommends changes to the CV of the candidate with the aim of increasing the likelihood of selection for an interview. These recommendations are exclusively shared with the candidate. Its use is initiated and managed by the candidate, outside of the potential employer's control.",
"anx3-094": "AI system intended to be used for assisting candidates in finding the best available position. The system is used by candidates to analyse both job vacancies and information provided by the candidate covering their skills, experience, and professional expectations. Based on these elements, the system ranks job vacancies and recommends the most suitable positions for the candidate. These recommendations are exclusively shared with the candidate. Its use is initiated and managed by the candidate, outside of the potential employer's control.",
"anx3-096": "AI system intended to be used for recognising and organising information in CVs received for an open position within an internal database that can be searched by recruiters.",
"anx3-101": "An online tutoring platform deploys an AI system to manage self-employed teacher accounts. Inputs include student satisfaction ratings, lesson completion rates, and punctuality logs from the videoconferencing system. The system aggregates these into a 'tutor performance score'. If the score falls below 4/5 for three consecutive weeks, the system automatically suspends the tutor's account for a month. If low ratings persist for another review period, the account is permanently deactivated, and the tutor can no longer accept lessons on the platform.",
"anx3-109": None,  # handled below by trimming
"anx3-112": "An AI system intended to decide on the grant of unemployment benefits in individual cases. The system analyses whether the person qualifies for the benefit, during which period and in which amount, and makes a recommendation to a case handler about the eligibility and the receiving of the benefits.",
"anx3-114": "An AI system intended to be used by public administrations to evaluate a natural person's eligibility for social housing or unemployment benefits through a scoring system. The system draws on demographic, behavioural, and financial data to predict the likelihood of fraud or long-term dependency.",
"anx3-128": "An AI system intended to create a numerical representation of a natural person's creditworthiness, based on their payment behaviour and income, that is intended to support the decision-making on a consumer credit or a mortgage.",
"anx3-131": "An AI system intended to perform advanced segmentation to gain a deeper understanding of customer groups and how they use certain services based on demographic and behavioural data, or pricing simulations used to test how changes in pricing might affect customer behaviour, competitiveness or profitability, distinct from any creditworthiness assessment.",
"anx3-132": "AI systems intended for customer support for credit applicants: they may assist applicants in understanding or completing the credit application form (e.g. by explaining terminology) or provide dynamic feedback on how specific answers may influence the likelihood of approval. They support applicants in preparing their credit application but do not participate in the formal credit-scoring assessment.",
"anx3-134": "An AI system intended solely for monitoring credit exposures for internal prudential purposes (to track and analyse credit-related activity, assess borrower risk and detect early warning signs of default or financial distress) after credit is granted.",
"anx3-136": "An AI system intended to be used by financial intermediaries solely to evaluate the extension of margin credit (whereby clients borrow capital against their existing securities) to existing or prospect clients, offered as a non-essential private service.",
"anx3-137": "An AI system intended to be used by an insurer that reviews applications for life insurance. The AI system processes data provided by the applicant, such as age, health status, family history, lifestyle habits and occupation, and relies on mortality tables that estimate the probability of death for each applicant within a given period. This processing guides whether the insurer accepts the application and what conditions apply.",
"anx3-139": "AI systems intended to be used for claims management in health insurance when the insured event happens, to verify whether a claim is valid under the policy terms or to determine the amount to be paid, including validating claimant information against various databases.",
"anx3-140": "AI systems intended to be used in product design for life insurance. They support a data-driven approach to product design by analysing large volumes of demographic, behavioural, and socio-economic data. By identifying emerging customer needs, risk patterns, and coverage gaps, the AI system enables insurers to create tailored life insurance products that are both relevant and competitively priced. For example, these AI systems can detect underserved segments and recommend product features or pricing models suited to their profiles. Scenario simulations and predictive modelling may help to assess the potential impact of new product offerings before launch. The system does not evaluate an individual natural person's risk profile to determine whether to offer, decline, revoke or deliver insurance to them.",
"anx3-145": "AI systems used in emergency departments of medical institutions that are intended to prioritise patients, without performing clinical assessment, medical acts or diagnostic functions.",
"anx3-146": "An AI system intended to be used to support decisions on allocating resources and pre-positioning assets to combat wildfires, where the system not only predicts the likelihood and the direction of wildfire evolution across an area's protected forests, but also automatically triggers the dispatching of emergency first response services or provides clear recommendation of staff allocation in order to contain the wildfire. The system supports staff rather than replacing human decision-making.",
"anx3-148": "An AI system intended to transcribe poor-quality emergency calls, or calls where callers may be panicked or unable to communicate, identifying relevant keywords and transcribing them automatically, thereby saving time that the call-taker would otherwise spend asking the caller to repeat themselves. The system does not evaluate or classify the call.",
"anx3-156": "AI systems intended to be used to analyse the risk that a specific environment/location will see offending and victimisation (i.e., people in certain areas will become victims of crime). Being environment/location-focused, such a system does not assess risks to specific persons.",
"anx3-157": "Situational awareness AI systems intended to be used to support law enforcement during the initial stages of responding to a reported crime scene. Such a system can be deployed via a robot or drone, and is designed to process visual and contextual inputs to detect critical elements, such as presence of armed individuals, weapons or environmental hazards, evaluating the immediate environment rather than specific individuals.",
"anx3-158": "AI systems intended to be used to identify road segments or times where road traffic accidents are likely to occur. Such systems are location-focused and do not analyse risks linked to concrete persons.",
"anx3-159": "AI-based video analytics intended to be used to predict overcrowding, stampedes, or structural hazards at large gatherings.",
"anx3-160": "AI flood-risk and wildfire-spread models intended to be used to identify populations at risk of becoming victims of accidents or natural catastrophes.",
"anx3-174": "An AI system that checks whether all required fields are completed in a probation officer's risk assessment form or flags inconsistencies in entered data (e.g., mismatched dates of offence or custody period). It does not evaluate personal characteristics.",
"anx3-176": "AI systems analysing neighbourhoods and assigning criminality scores (predictive crime mapping systems), without assessing individual persons.",
"anx3-023": "AI system to categorise customers based on their gender to offer/improve personalised experience for customers. The AI system captures keystrokes, analyses them to assign a gender to the customer to offer/improve personalized experience (e.g., personalised advertising).",
"anx3-184": "An AI system intended to process licence-plate reads and travel-time data in order to flag vehicles with unusually long journeys and route the vehicle to a general secondary lane for a technical inspection, without creating or implying a risk assessment about the driver or passengers.",
"anx3-185": "An AI system intended to monitor vehicles transiting a border crossing point to flag stolen vehicles for secondary checks.",
"anx3-187": "An AI system intended to provide applicants with answers to frequently asked questions, to guide users to the correct forms, to schedule appointments, or to deliver application status notifications. Its intended purpose is service delivery to migrant applicants.",
"anx3-189": "An AI system intended to highlight verbatim differences between current and previous statements (for example, string-level contrasts), without generating any credibility assessment or recommending follow-up questions.",
"anx3-198": "An AI system embedded in a maritime or unmanned platform used by border authorities, where it is intended and technically limited to collision avoidance (for example detecting obstacles, including persons, only to prevent impacts and without generating alerts for interception, tracking, triage or any border-control response).",
"anx3-199": "An AI system intended to analyse historical data to identify patterns of document fraud and to inform general indicators or staffing, without person detection.",
"anx3-202": "An AI speech-to-text system used by a court to transcribe audio recordings of court proceedings and hearings, which then become part of the file. The system (i) takes various audio file formats (or live audio) and produces textual transcripts, including automated speaker separation (distinguishing different voices) and insertion of punctuation; (ii) corrects terminology, for example recognising legal terms or names and adjusting the vocabulary accordingly. Its intended purpose is limited to technical recording or transcription without analytical or evaluative functionalities.",
"anx3-203": "AI-enabled chatbots offered on the websites of courts to assist visitors to the website in finding relevant information. Such systems function as virtual assistants, and are designed to provide information to individuals about procedural steps, required documents, deadlines, and available remedies.",
"anx3-204": "An AI system designed to assist judicial authorities in drafting press releases or legal summaries on public interest cases. The system translates the technical language of a judgement into accessible summaries.",
"anx3-206": "AI systems intended for purely ancillary administrative activities, such as the anonymisation or pseudonymisation of judicial decisions, documents, or data; internal communication between personnel; searching for delivery addresses and dispatching documents; verifying the payment of court fees; processing electronic signatures; verifying powers of attorney; and other similar administrative tasks.",
"anx3-208": "An AI system performing data analysis for the purpose of metadata extraction based on the facts of the file (e.g. extraction of procedural roles from the claim (parties, legal representatives, witnesses, experts, etc.)) to support clerical work such as summons.",
"anx3-209": "An AI system intended for proofreading or improving the style of judicial decisions or judgments drafted by judges, without changing the content.",
"anx3-214": "AI systems monitoring the activity of elected officials in submitting legislative proposals or amendments based on content provided by a parliament's web presence, for informational purposes.",
"anx3-215": "AI systems deployed by sociological agencies for the purpose of collecting, analysing, and presenting information in an objective and transparent manner, with the sole function of informing the public or relevant stakeholders.",
"anx3-216": "AI systems used by academic institutions for modelling electoral behaviour for research purposes.",
"anx3-217": "AI systems for counting ballots automatically, used only for mechanical recognition and tallying of ballots (e.g. scanning, OCR).",
"anx3-218": "An AI-enabled chatbot designed to provide information to voters on behalf of election authorities, operating in a politically neutral way (e.g. providing information when the elections take place, where a person can vote, voting times, etc.).",
}

# anx3-109: keep the auto result but drop its final legal-test sentence.
TRIM_SENTENCES = {
    "anx3-109": ["does not represent task allocation on the basis of individual behaviour"],
}


# ---------------------------------------------------------------------------
# Reviewer pass (Rah, 25 Sep 2026): 76 hand-edited rows reviewed, 46 marked
# "fix" with his own replacement text (redaction_user_review.json). Decision:
# use the reviewer's text, but strip EXPLICIT verdicts only (statements of the
# label, the exception, or a legal citation). Legal-test wording the reviewer
# restored (e.g. "not emotion recognition", "no material impact on the
# decision-making") is kept by his choice and disclosed as a limitation.
VERDICT_STRIPS = {
    "anx3-016": [(" as indicated in Recital 54 AI Act.", ".")],
    "anx3-053": [(" should be classified as high-risk.", ".")],
    "anx3-072": [(" should not be considered high- risk. Since the system’s output is used", ". The system’s output is used")],
    "anx3-080": [(" should be classified as high-risk.", ".")],
    "anx3-112": [(" Such an AI system is high-risk, because it is intended to evaluate a natural person’s eligibility, and makes a recommendation on the granting or denial of these benefits.", "")],
    "anx3-114": [(" that is not a prohibited practice.", "."),
                 (" Such an AI system is high-risk, since it aids in the evaluation of a natural person’s eligibility and materially influences decision about whether the applicant will receive the benefits and services.", "")],
    "anx3-128": [(", which qualify as essential private services.", ".")],
    "anx3-137": [(", so long as it qualifies as a risk assessment as defined above.", ".")],
    "anx3-189": [("; where the system evaluates the significance of the differences or labels them as credibility concerns, the exception no longer applies.", ".")],
    "anx3-202": [("facts and the law100.", "facts and the law.")],
    "anx3-209": [(" In any event, the system would benefit from the exception for AI systems intended to improve the result of a previously completed human activity.", "")],
}
